apiVersion: v1
kind: Service
metadata:
  name: {{ include "wpMysql.fullname" . }}
  labels: {{- include "wpMysql.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service_mysql.port }}
  selector: {{- include "wpMysql.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wpMysql.fullname" . }}-mysql-pvc
  labels:
     {{- include "wpMysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote}}
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ include "wpMysql.fullname" . }}
  labels:
     {{- include "wpMysql.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
     {{- include "wpMysql.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
     {{- include "wpMysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "mysql:{{ .Values.imageTagMysql}}"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
#          valueFrom:
#             secretKeyRef:
#                 name: mysql-secret
#                 key: mysql-root-password 
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   failureThreshold: 2
        #   initialDelaySeconds: 10
        #   periodSeconds: 15
        # livenessProbe: #С этой конфигурацией kubelet будет пытаться открыть сокет к вашему контейнеру на определённый порт. 
        #   tcpSocket: # Если он сможет установить соединение, контейнер будет считаться здоровым, если нет, будет считаться заваленным.
        #     port: 3306
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        resources: # використовується для контролю ресурсів в кластері
{{ toYaml .Values.resources | indent 10}}
        ports:
        - containerPort: {{ .Values.serviceMysql.port }}
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "wpMysql.fullname" . }}-mysql-pvc
